WIDTH = 800
HEIGHT = 750

PADDING_LASER = 92
SLEEPING = 0.001
N_LIVES = 3
MOVE_STEP = 1
SHOT_MOVE = 40

DEFENSE_START_X = -250
DEFENSE_START_Y = -200
DEFENSE_OG_GAP = 5
DEFENSE_HEIGHT = 250
DEFENSE_HEIGHT_SMALL = 10
DEFENSE_X_GAP = 3
DEFENSE_REPEAT = 3
DEFENSE_DESTROY_PIXELS = 25
DEFENSE_COLOR = "green"
DEFENSE_BG_COLOR = "black"

INVADERS_ROWS = 3
INVADERS_COLS = 8
INVADER_HEIGHT = 35